return {
  "pmizio/typescript-tools.nvim",
  -- enabled = false,
  dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
  event = { "BufReadPre", "BufNewFile" },
  opts = {
    filetypes = {
      "javascript",
      "javascriptreact",
      "javascript.jsx",
      "typescript",
      "typescriptreact",
      "typescript.tsx",
      "vue",
    },
    settings = {
      expose_as_code_action = "all",
      tsserver_max_memory = "auto",
      tsserver_plugins = {
        "@vue/typescript-plugin",
      },
      tsserver_file_preferences = {
        "javascript",
        "javascriptreact",
        "javascript.jsx",
        "typescript",
        "typescriptreact",
        "typescript.tsx",
        "vue",
        importModuleSpecifierPreference = "non-relative",
        includeInlayParameterNameHints = "all",
        includeInlayParameterNameHintsWhenArgumentMatchesName = true,
        includeInlayFunctionParameterTypeHints = true,
        includeInlayVariableTypeHints = true,
        includeInlayVariableTypeHintsWhenTypeMatchesName = true,
        includeInlayPropertyDeclarationTypeHints = true,
        includeInlayFunctionLikeReturnTypeHints = true,
        includeInlayEnumMemberValueHints = true,
        includeCompletionsForModuleExports = true,
        providePrefixAndSuffixTextForRename = false,
        quotePreference = "auto",
      },
    },
  },
}
