format = """
[ ┌───────────]\
(bold white)\
[󰉕  ](bold bg:none fg:green)\
(bold bg:none fg:green)\
[\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
]\
(bold bg:purple fg:black)\
$singularity\
$kubernetes\
$directory
[ │ ]\
(bold white)\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$gradle\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$cmd_duration\
$line_break\
[ └───](bg:none fg:white)\
$status\
$character\
"""
[fill]
symbol = " "

[username]
show_always = true
style_user = "bold fg:white"
style_root = "bold fg:white"
format = "[$user]($style)"

[git_branch]
symbol = " "
format = " on [$symbol$branch]($style) "
style = "bold bg:purple fg:black"

[git_commit]
style = "bold bg:purple fg:black"

[git_state]
style = "bold bg:purple fg:black"

[git_status]
style = "bold bg:purple fg:black"

[time]
disabled = false
format = "[$time]($style)"
style = "bg:white fg:black"

[directory]
read_only = " "
truncation_length = 3
truncation_symbol = "./"
style = "bold bg:none fg:green"

[status]
symbol = " "
disabled = false

[character]
success_symbol = "[󰣉 ](bold bg:none fg:white)"
error_symbol = "[󰣉 ](bold red)"
vicmd_symbol = "[󰣉 ](bold yellow)"
