gui:
  theme:
    selectedLineBgColor:
      - "#313244"
keybinding:
  commits:
    moveDownCommit: "D"
    moveUpCommit: "U"
git:
  paging:
    colorArg: always
    # useConfig: false
    pager: delta --dark --paging=never --syntax-theme base16-256 --diff-so-fancy -s # (-s for split)
os:
  editPreset: "nvim"
