gui:
  theme:
    selectedLineBgColor:
      - "#313244"
keybinding:
  commits:
    moveDownCommit: "D"
    moveUpCommit: "U"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
